spring.datasource.url=jdbc:mysql://mysql-10eb640f-systemsjackal-7bb2.i.aivencloud.com:12396/defaultdb?sslMode=REQUIRED

spring.datasource.username=avnadmin
spring.datasource.password=AVNS_hak8sBvrJvkz2zwheWS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080